controller_manager:
  ros__parameters:
    update_rate: 50
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    position_trajectory_controller:
      type: position_controllers/JointTrajectoryController
      joints:
        - joint1
        - joint2
        - joint3
      state_publish_rate: 50
      command_publish_rate: 50
      constraints:
        goal_time: 0.5
      gains:
        joint1: {p: 100.0, d: 10.0, i: 1.0}
        joint2: {p: 100.0, d: 10.0, i: 1.0}
        joint3: {p: 100.0, d: 10.0, i: 1.0}
