<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="simple_arm">

  <!-- Parametri -->
  <xacro:property name="base_radius" value="0.1"/>
  <xacro:property name="base_length" value="0.2"/>
  <xacro:property name="arm_radius" value="0.05"/>
  <xacro:property name="arm_length" value="1.0"/>
  <xacro:property name="arm_mass" value="0.5"/>
  <xacro:property name="base_mass" value="1.0"/>

  <!-- Materiali -->
  <xacro:property name="base_color" value="0.5 0.5 0.5 1.0"/>
  <xacro:property name="arm_color" value="0.0 0.0 1.0 1.0"/>

  <!-- Link della base -->
  <link name="base_link">
    <visual>
      <geometry>
        <cylinder radius="${base_radius}" length="${base_length}"/>
      </geometry>
      <material>
        <color rgba="${base_color}"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${base_radius}" length="${base_length}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="${base_mass}"/>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="0.01" ixy="0" ixz="0" iyy="0.01" iyz="0" izz="0.01"/>
    </inertial>
  </link>

  <!-- Link del braccio -->
  <link name="arm_link">
    <visual>
      <geometry>
        <cylinder radius="${arm_radius}" length="${arm_length}"/>
      </geometry>
      <material>
        <color rgba="${arm_color}"/>
      </material>
    </visual>
    <collision>
      <geometry>
        <cylinder radius="${arm_radius}" length="${arm_length}"/>
      </geometry>
    </collision>
    <inertial>
      <mass value="${arm_mass}"/>
      <origin xyz="0 0 0.5" rpy="0 0 0"/>
      <inertia ixx="0.005" ixy="0" ixz="0" iyy="0.005" iyz="0" izz="0.005"/>
    </inertial>
  </link>

  <!-- Giunto tra base e braccio -->
  <joint name="base_to_arm_joint" type="revolute">
    <parent link="base_link"/>
    <child link="arm_link"/>
    <origin xyz="0 0 ${base_length/2}" rpy="0 0 0"/>
    <axis xyz="0 0 1"/>
    <limit lower="-1.57" upper="1.57" effort="10.0" velocity="1.0"/>
  </joint>
</robot>
